# Generated by Django 4.1.1 on 2022-09-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="update_at", new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="desc",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
