# Generated by Django 4.1.1 on 2022-09-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_users", "0002_rename_update_at_task_updated_at_alter_task_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="desc",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_finished",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_published",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
